name: LaunchPadのHexoBlogBuild
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install & Build
        run: |
          npm install -g hexo-cli
          npm install
          hexo generate
          echo "lpblog.rdpstudio.top" > ./public/CNAME
          ls public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Update docs abbrlink
        run: |
          rm -r node_modules
          rm -r public
          rm -f package-lock.json
          git add source
          git diff HEAD --exit-code
          if [ $? -eq 0 ]
          then
              echo "No changes to commit!"
          else
              git config --global user.name "github-actions-blog[bot]"
              git config --global user.email "noreply@rdpstudio.top"
              git commit -m "[skip ci] Updated abbrlink"
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
              git push origin main
          fi