name: LaunchPadのHexoBlogBuild
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install & Build
        run: |
          npm install -g hexo-cli
          npm install
          hexo generate
          echo "lpblog.rdpstudio.top" > ./public/CNAME
          ls public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - name: Update docs abbrlink
        run: |
          git fetch --all
          git reset --hard origin/main
          git reset --hard origin/gh-pages
          git add .
          git diff HEAD --exit-code
          if [ "$EXCODE" != "0" ]; then  
             "No changes to commit!"
          else
            git config --global user.name "github-actions-blog[bot]"
            git config --global user.email "noreply@rdpstudio.top"
            git commit -m "[skip ci] Updated abbrlink from commit $env:GITHUB_SHA on $env:GITHUB_REF"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push origin main
          fi