name: LaunchPadのHexoBlogBuild
on:
  - workflow_dispatch
  push:
  branches:
    - main
jobs:
  buildstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install & Build
        run: |
          npm install -g hexo-cli
          npm install
          hexo generate
          echo "lpblog.rdpstudio.top" > ./public/CNAME
          ls public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public